<?php
namespace app\models\article;

use core\Models;

class Article extends Models {
    public $id;
    public $title;
    public $intro;
    public $image;
    public $content;
    public $create_time;

    static public function getTable(){
        return "article";
    }

    static public function attributeLabels()
    {
        return array(
            'id'=>"ID",
            'title'=>"标题",
            'intro'=>"介绍",
            'image'=>"封面",
            'content'=>"内容",
            'create_time'=>"创建时间",
        );
    }

    public function beforeSave()
    {
        $this->create_time = time();

        return parent::beforeSave(); // TODO: Change the autogenerated stub
    }
}