<?php
namespace app\models\user;

use core\Models;

class User extends Models {
    public $id;
    public $username;
    public $password_hash;
    public $name;
    public $phone;
    public $create_time;

    static public function getTable(){
        return "user";
    }

    static public function attributeLabels()
    {
        return array(
            'id'=>"ID",
            'username'=>"用户名",
            'password'=>"密码",
            'name'=>"名称",
            'phone'=>"电话",
            'create_time'=>"创建时间",
        );
    }

    public function beforeSave()
    {
        return parent::beforeSave(); // TODO: Change the autogenerated stub
    }

    public function load($data = array())
    {
        if($data["password"])
            $this->setPassword($data["password"]);

        return parent::load($data); // TODO: Change the autogenerated stub
    }

    public function setPassword($password){
        $this->password_hash = md5($password);
    }

    static public function login($username,$password){
        if(empty($username))
            return null;

        $result = User::findOne(array(
            "username"=>$username,
            "password_hash"=>md5($password)
        ));

        return $result;
    }
}